version: '3'

services:
  nginx:
    image: centos/nginx-112-centos7
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/openconnect/data/nginx:/etc/nginx/conf.d
