nginx:
  image: nginx
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/www:/var/www
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NGINX_HOST=www0.music-tm.com
    - NGINX_PORT=80
    - NGINX_PORT_SSL=443
    
  